### ISSUE TITLE
PMPP 201 youtube plugin

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#267]
### URL
https://learn.twu.ca/course/view.php?id=8951&section=8
### Instructions
plugin isn't working.  Please check Unit 7, topic 4, FAR Centre Activity 7.4.1 & Personal Activity 8.0.5-7
![image](https://user-images.githubusercontent.com/35148983/76874169-675da580-6834-11ea-8f6c-e7a254d2081b.png)

**Comment by faitht1023** [comment]
Fixed. The link previous was starting the video exactly at 84s into the video, however, now with what I've done, it starts just at the very beginning. Were you wanting the video to start at 84s?

**Comment by cmadland** [comment]
The youtube plugin doesn’t work with a ’start time’ in the url.

Colin


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Mar 23, 2020, at 12:24 PM, faitht1023 <notifications@github.com<mailto:notifications@github.com>> wrote:



Fixed. The link previous was starting the video exactly at 84s into the video, however, now with what I've done, it starts just at the very beginning. Were you wanting the video to start at 84s?

**Comment by kmarjanovic** [comment]
@cmadland @faitht1023 
I tried removing the seconds earlier - and again now - and the plugin still doesn't work.
Ideas?
![image](https://user-images.githubusercontent.com/35148983/77471231-87164000-6dd7-11ea-804e-a3758e32ed39.png)

**Comment by rezakh66** [comment]
@kmarjanovic It's fixed now.

**Comment by rezakh66** [comment]
@kmarjanovic Do you want videos in the activity checklist as well? I see your Note to Matt in this section.

**Comment by cmadland** [comment]
ok…for future reference, the time hash is the &t=53s…including the ampersand. If you delete that, it should work.


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
604.513.2121 ext. 3876 |  colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

Trinity Western University is located on the traditional, ancestral, and unceded territory of the Sto:lo people.

On Mar 24, 2020, at 2:37 PM, rezakh66 <notifications@github.com<mailto:notifications@github.com>> wrote:



@kmarjanovic<https://github.com/kmarjanovic> It's fixed now.

**Comment by kmarjanovic** [comment]
oh okay.  Thank you!!
