### ISSUE TITLE
LDRS 611 - Gradebook set-up

### ISSUE THREAD

**Issue by kmarjanovic** [TWUOnline/bug-tracking#971]
### Instructions
Please help fix the gradebook for Shawna's course: [LDRS 611 OL SP 2024](https://learn.twu.ca/grade/edit/tree/index.php?id=31058). 

I've added the correct categories in the [working master](https://learn.twu.ca/grade/edit/tree/index.php?id=30337) but need the values to reflect the correct % - Participation 30%, Individual Paper 30%, Team Project 40%.

Thank you!

**Comment by chloecwh** [comment]
I'm on it

**Comment by chloecwh** [comment]
done @kmarjanovic

**Comment by kmarjanovic** [comment]
@chloecwh I still don't see it... https://learn.twu.ca/grade/edit/tree/index.php?id=31058

**Comment by chloecwh** [comment]
@kmarjanovic just updated the 2024 shell as well. Thanks for the patience!

**Comment by kmarjanovic** [comment]
Perfect!  Thanks so much Chloe!!
